### PR TITLE
Fix for Names truncated at 256 bytes

### PR DESCRIPTION
**Pull request by pmqs**
Partial fix for https://github.com/zlib-ng/minizip-ng/issues/690

Heavy use of `malloc`/`realloc` in this, so have tested this for leaks/corruption by hacking sanitizer into the build. There are some leaks around `mz_crypt_sha_create` and `mz_zip_writer_entry_open` that were already there, so haven't made it worse.

Can post the sanitizer patch if you like.

### CODE REVIEW

**Comment by pmqs** [comment]
Created https://github.com/zlib-ng/minizip-ng/issues/717 to report the leaks and hacked sanitizer build is in https://github.com/pmqs/minizip-ng/tree/sanitizer

**Comment by nmoinvaz** [comment]
I am second guessing whether or not just to use malloc or not. Because alloca requires headers depending on the platform. And also can cause problem/exeception if there isn't enough stack space. I agree it is unlikely, but who knows.  alloca is more efficent if using lots of small files in a zip though.

**Comment by pmqs** [comment]
Yep, I was in two minds about that myself. In the end I decided to avoid hitting the heap when I could keep it all on the stack with  `alloca`.  It will be exceptional use-cases of very long filenames/paths (which this fix is designed to address) that will be the problem.

If you think `malloc` is likely to have less portability issues, I can redo the change easily enough.

**Comment by pmqs** [comment]
Changed the `alloca` to `malloc` for now.

**Comment by nmoinvaz** [comment]
I have cleaned up and incorporated these changes.

**Pull request closed without merging**
